In [9]:
#importar la librería numpy:

import numpy as np

In [10]:
#arreglo unidimensional (vector):

#creando un arreglo a partir de una lista de números:
A = np.array([12, 14, 21, 18, 20, 4,23])
A[-1:3:-1]


array([23,  4, 20])

In [11]:
teta = np.arange(0,70,10)

#ang: arreglo de angulos (en radianes)
ang = np.deg2rad(teta)
an=np.sin(90)
print(teta)
print(ang)
print(an)


[ 0 10 20 30 40 50 60]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755]
0.8939966636005579


In [31]:
#Solo complete el código donde se debe (no cambie la estructura del programa)
import numpy as np

a = 1.55
N = 12

#arreglo de tiempos
t = np.linspace(0,10,12)

#arreglo de velocidades
v = a*t

#arreglo de distancia
d = (1/2)*a*(t**2)

print("tiempo  distancia   velocidad")
for tiempo,distancia,velocidad in zip(t,d,v):
    print("{:.2f}\t{:6,.2f}\t{:10,.2f}".format(tiempo,distancia,velocidad))
    
print("\nTiempos donde el coche alcanzó velocidades en el intervalo [6,10] m/s")
indices = t[6:10]
print(indices)
for temp in indices:
    print(temp)

tiempo  distancia   velocidad
0.00	  0.00	      0.00
0.91	  0.64	      1.41
1.82	  2.56	      2.82
2.73	  5.76	      4.23
3.64	 10.25	      5.64
4.55	 16.01	      7.05
5.45	 23.06	      8.45
6.36	 31.38	      9.86
7.27	 40.99	     11.27
8.18	 51.88	     12.68
9.09	 64.05	     14.09
10.00	 77.50	     15.50

Tiempos donde el coche alcanzó velocidades en el intervalo [6,10] m/s
[5.45454545 6.36363636 7.27272727 8.18181818]
5.454545454545454
6.363636363636363
7.2727272727272725
8.181818181818182


In [5]:
B=np.array([45, 23, 89, 100, 23, -56])
print(B)
print(type(B))

[ 45  23  89 100  23 -56]
<class 'numpy.ndarray'>


In [11]:
A = np.array([45, 23, 89, 100, 23, -56])

print("Numero de elementos: ",A.size)
print("Dimensiones: ",A.ndim)
print("Forma: ",A.shape)
print("Tipo de dato: ",A.dtype)
print("Bytes de memoria por elemento: ",A.itemsize)

Numero de elementos:  6
Dimensiones:  1
Forma:  (6,)
Tipo de dato:  int32
Bytes de memoria por elemento:  4


In [16]:
A = np.array([45, 23, 89, 100, 23, -56])

A[0]=100   #el arreglo es mutable
print(A)

A[-1]=10.5
print(A)

A[2] = "60"
print(A)

A[-1] = 'a'

[100  23  89 100  23 -56]
[100  23  89 100  23  10]
[100  23  60 100  23  10]


ValueError: invalid literal for int() with base 10: 'a'

In [18]:
from random import uniform

#creando una lista de un millon de números aleatorios reales
temp_c = [uniform(20,30) for i in range(1000000)]

#print(temp_c)
print(temp_c[0],temp_c[1],temp_c[2])

29.196895505922324 23.795167552328294 29.943038501035353


In [20]:
#se desea convertir cada elemento de temp_c en grados F:
array_c = np.array(temp_c)
array_f = 9*array_c/5 + 32

In [6]:
print("r")

r


In [22]:
A = np.array([45, 23, 89, 100, 23, -56])

A = np.append(A,10)
print(A)

[ 45  23  89 100  23 -56  10]


In [20]:
A = np.arange(20)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [56]:

import numpy as np

velArena = 3.5
velCamino = 5
w = 4.5
u = 14
#teta: arreglo de angulos (en grados)
teta = np.arange(0,70,10)

#ang: arreglo de angulos (en radianes)
ang = np.deg2rad(teta)

b=np.sin(10)
c=b*a
z = np.hypot(w,c)
print(z)
print(c)


#tiempos:  arreglo de tiempos calculados
tiempos = z/3.5+((u-a)/5)

print("angulo(grados)   tiempo")
print(tiempos)
#for angulo,t in zip(teta,tiempos):
 #   print("{:8.2f}\t{:6.3f}".format(angulo,t))

4.509721910648901
0.295958969093304
angulo(grados)   tiempo
4.197296196648988


In [53]:
A = np.arange(1,5,0.25)
print(A)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75]


In [26]:
#ejemplo aplicativo:

a = 1.3 #aceleración uniforme
t = np.arange(0,10.5,0.5)
d = 0.5*a*t**2

print("   TIEMPO   DISTANCIA")
print("   ------   ---------")
for val_t,val_d in zip(t,d):
    print("{:>6.2f} seg {:>6.2f} m".format(val_t,val_d))

   TIEMPO   DISTANCIA
   ------   ---------
  0.00 seg   0.00 m
  0.50 seg   0.16 m
  1.00 seg   0.65 m
  1.50 seg   1.46 m
  2.00 seg   2.60 m
  2.50 seg   4.06 m
  3.00 seg   5.85 m
  3.50 seg   7.96 m
  4.00 seg  10.40 m
  4.50 seg  13.16 m
  5.00 seg  16.25 m
  5.50 seg  19.66 m
  6.00 seg  23.40 m
  6.50 seg  27.46 m
  7.00 seg  31.85 m
  7.50 seg  36.56 m
  8.00 seg  41.60 m
  8.50 seg  46.96 m
  9.00 seg  52.65 m
  9.50 seg  58.66 m
 10.00 seg  65.00 m


In [27]:
#uso del método linspace:

A = np.linspace(0,10) #se crean por defecto 50 elementos
print(A)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [28]:
A = np.linspace(0,10,12)
print(A)

[ 0.          0.90909091  1.81818182  2.72727273  3.63636364  4.54545455
  5.45454545  6.36363636  7.27272727  8.18181818  9.09090909 10.        ]


In [7]:
#ejemplo aplicativo:

R=55

a = np.arange(5,100.25,0.25)
b = np.sqrt(4*R**2 - a**2)
area = (a-8)*(b-20)

areaMaxima = np.max(area)

#for va,vb,varea in zip(a,b,area):
 #   print("{:.3f}{:10.3f}{:10.3f}".format(va,vb,varea))
    
print("Area máxima: ",areaMaxima)

Area máxima:  4051.8799631262677


In [31]:
#indexación booleana:

A = np.array([50, 45, 89, 10, 11, 45, 18, 21])

A_pares = A[A%2==0]
print(A_pares)

[50 10 18]


In [32]:
arr = np.array([4, 8, 3, 8, 10, 44])

arr%2==0

array([ True,  True, False,  True,  True,  True])

In [33]:
print(arr%2==0)

[ True  True False  True  True  True]


In [34]:
arr = np.array([4, 8, 3, 8, 10, 44])

arr>9

array([False, False, False, False,  True,  True])

In [35]:
print(arr>9)

[False False False False  True  True]


In [36]:
arr = np.array([4, 8, 3, 8, 10, 44])

arr[1:4]

array([8, 3, 8])

In [37]:
print(arr[1:4])

[8 3 8]


In [43]:
#creando un arreglo unidimensonal de 31 elementos aleatorios reales
#en el rango [24, 32>

temp_ene = np.random.uniform(24,32,(31,))
print(temp_ene)

print("\nTemperaturas por encima de los 30 grados: ")
print(temp_ene[temp_ene>30])

print("\nTemperaturas por encima del promedio del mes: ")
prom = np.mean(temp_ene)
print(prom)
print(temp_ene[temp_ene>prom])

print("\nTemperaturas entre 28 y 29 grados: ")
print(temp_ene[(temp_ene>28) & (temp_ene<29)]) #and : &
                                               #or: |
                                               #not: !

[31.43822725 29.29898286 24.68115299 27.40172393 25.31822352 26.30163331
 30.86782641 25.78167746 24.47404505 26.91033358 30.55603188 25.65424397
 28.96947447 27.44336331 27.39237896 26.16174515 31.7592826  29.88848727
 31.26175262 27.15067104 31.00229071 29.04005983 25.92447441 26.49446379
 25.72591239 31.30380257 29.3718202  24.72904609 30.65191959 28.30513578
 24.85048752]

Temperaturas por encima de los 30 grados: 
[31.43822725 30.86782641 30.55603188 31.7592826  31.26175262 31.00229071
 31.30380257 30.65191959]

Temperaturas pr encima del promedio del mes: 
27.939053887302475
[31.43822725 29.29898286 30.86782641 30.55603188 28.96947447 31.7592826
 29.88848727 31.26175262 31.00229071 29.04005983 31.30380257 29.3718202
 30.65191959 28.30513578]

Temperaturas entre 28 y 29 grados: 
[28.96947447 28.30513578]


In [45]:
#uso del método where:

arr = np.array([5, 10, 11, 45, 19, 22, 90])

#¿en qué indices se encuentran los pares de arr?
t = np.where(arr%2==0)
print(t)

a_indices_pares = t[0]
print(a_indices_pares)

(array([1, 5, 6], dtype=int64),)
[1 5 6]


In [46]:
a_indices_pares = np.where(arr%2==0)[0]
print(a_indices_pares)

[1 5 6]


In [50]:
#ejemplo aplicativo (continuación):

R=55

a = np.arange(5,100.25,0.25)
b = np.sqrt(4*R**2 - a**2)
area = (a-8)*(b-20)

areaMaxima = np.max(area)

#for va,vb,varea in zip(a,b,area):
#    print("{:.3f}{:10.3f}{:10.3f}".format(va,vb,varea))
    
#print("Area máxima: ",areaMaxima)

p = np.where(area==areaMaxima)[0][0]
print(p)

print("El afiche deberia tener dimensiones: ",a[p],b[p])

278
El afiche deberia tener dimensiones:  74.5 80.93052576129726


In [12]:
#introducción a los arreglos bidimensionales (matrices)

A = np.array([[3,6,4,5], [1,2,3,4], [6,9,8,9]])
print(A)

print("Numero de elementos: ",A.size)
print("Dimensiones:",A.ndim)
print("Forma: ",A.shape)
print("Tipo de dato: ",A.dtype)

[[3 6 4 5]
 [1 2 3 4]
 [6 9 8 9]]
Numero de elementos:  12
Dimensiones: 2
Forma:  (3, 4)
Tipo de dato:  int32


In [13]:
#accediendo a los valores del arreglo:

print(A[0,0],'\n')
print(A[-1,-1],'\n')
print(A[:,2],'\n')
print(A[1,:],'\n')
print(A[0:2,1:4],'\n')
print(A[[1,2],:])

3 

9 

[4 3 8] 

[1 2 3 4] 

[[6 4 5]
 [2 3 4]] 

[[1 2 3 4]
 [6 9 8 9]]


In [68]:
#TIP:

arr = np.random.randint(1,7,(2,10))
print(arr)

#sumando todos los elementos del arreglo arr:
asuma = np.sum(arr)
print(asuma)

#sumando los elementos de cada fila
asf = np.sum(arr,axis=1)

print(asf)

#sumando los elementos de cada columna
asc = np.sum(arr,axis=0)
print(asc)

#promediar los elementos de cada fila
apromf = np.mean(arr,axis=1)
print(apromf)

#promediar los elementos de cada columna
apromc = np.mean(arr,axis=0)
print(apromc)

[[5 6 2 2 6 3 4 4 3 4]
 [2 6 6 5 3 6 2 3 5 2]]
79
[39 40]
[ 7 12  8  7  9  9  6  7  8  6]
[3.9 4. ]
[3.5 6.  4.  3.5 4.5 4.5 3.  3.5 4.  3. ]


In [8]:
#TIP:
#tabular la función F(x)=(x^2+2)/(sin(x)+1) para x
#que pertenece al dominio [-5,5]

#creando el dominio x:
x = np.linspace(-5,5,100)

#creando el rango:
f = (x**2 + 2)/(np.sin(x)+1)

#imprimiendo la tabla:
print("   x    f(x)")
#for vx,vf in zip(x,f):
 #   print("{:.2f}  {:.2f}".format(vx,vf))

   x    f(x)
